version: '3.8'

services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/todoapp
    depends_on:
      - mongodb
    networks:
      - todo-network

  mongodb:
    image: mongo:7-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=todoapp
    networks:
      - todo-network

volumes:
  mongodb_data:

networks:
  todo-network:
    driver: bridge